name       : calibre
version    : 5.39.1
release    : 160
source     :
    - https://download.calibre-ebook.com/5.39.1/calibre-5.39.1.tar.xz : ddaffbdabae82e3b0c3446db07df55da99ad1ffefb257a845c051ffca3974ddc
homepage   : https://calibre-ebook.com/
license    : GPL-3.0-only
component  : office.viewers
summary    : Calibre eBook Library Manager
description: |
    calibre is a free and open source e-book library management application developed by users of e-books for users of e-books.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(dbus-python)
    - pkgconfig(hunspell)
    - pkgconfig(icu-i18n)
    - pkgconfig(libinput)
    - pkgconfig(libmtp)
    - pkgconfig(mtdev)
    - pkgconfig(poppler)
    - pkgconfig(python3)
    - pkgconfig(shared-mime-info)
    - pkgconfig(sqlite3)
    - pkgconfig(xkbcommon)
    - chmlib-devel
    - dnspython
    - hyphen-devel
    - liberation-fonts-ttf
    - libstemmer-devel
    - optipng
    - podofo-devel
    - pygments
    - pyqt-builder
    - python-apsw
    - python-beautifulsoup4
    - python-cchardet
    - python-css-parser
    - python-dateutil
    - python-feedparser
    - python-html2text
    - python-html5-parser
    - python-jeepney
    - python-markdown
    - python-mechanize
    - python-msgpack
    - python-pillow
    - python-psutil
    - python-qtwebengine
    - python-regex
    - python-sip
    - python-zeroconf
    - python3-qt5
    - speech-dispatcher
    - xdg-utils
    - xorg-server-xvfb
rundeps    :
    - dnspython
    - liberation-fonts-ttf
    - optipng
    - poppler-utils
    - pygments
    - python-apsw
    - python-beautifulsoup4
    - python-cchardet
    - python-css-parser
    - python-dateutil
    - python-feedparser
    - python-html2text
    - python-html5-parser
    - python-jeepney
    - python-markdown
    - python-mechanize
    - python-msgpack
    - python-pillow
    - python-psutil
    - python-qtwebengine
    - python-regex
    - python-zeroconf
    - python3-dbus
    - python3-qt5
    - speech-dispatcher
environment: |
    #Set XDG directories in fakeroot, add read privileges to /usr/share
    export CALIBRE_PY3_PORT=1
    export XDG_DATA_HOME=$installdir/usr/share
    export XDG_UTILS_INSTALL_MODE="user"
setup      : |
    %apply_patches
build      : |
    python3 setup.py build
    python3 setup.py gui
    python3 setup.py mathjax
install    : |
    install -dm00644 $installdir/usr/share/zsh/site-functions

    python3 setup.py install --root="%installroot%" --staging-root=%installroot%/usr --prefix=/usr
    %python3_compile

    # Restore read permissions for icons
    chmod -R +r $installdir/usr/share/icons

    # Remove MimeTypes from .desktop as it creates unwanted associations
    sed -e "/MimeType/d" -i  $installdir/usr/share/applications/calibre*.desktop
    rm -rfv $installdir/usr/share/applications/calibre-{ebook-*,lrfviewer}.desktop
    chmod -R 00755 $installdir/usr/share/applications/calibre-gui.desktop
    install -Dm00644 $workdir/resources/calibre-mimetypes.xml $installdir/usr/share/mime/packages/calibre-mimetypes.xml

    # Use system fonts
    rm $installdir/usr/share/calibre/fonts/liberation/*.ttf
    ln -s /usr/share/fonts/truetype/liberation/*.ttf $installdir/usr/share/calibre/fonts/liberation/

    # Empty folder, also calibre shouldn't own this
    rmdir $installdir/usr/share/desktop-directories

    # Remove unneeded files
    rm $installdir/usr/share/calibre/*portable*
check      : |
    # excluded tests for optional or missing packages python-unrardll python-pychm python-pycryptodome python-py7zr python-sgmllib3k
    xvfb-run python3 setup.py test \
        --exclude-test-name 7z \
        --exclude-test-name feedparser \
        --exclude-test-name import_of_all_python_modules \
        --exclude-test-name pychm \
        --exclude-test-name pycryptodome \
        --exclude-test-name qt \
        --exclude-test-name unrar
