name       : calibre
version    : 3.47.1
release    : 111
source     :
    - https://download.calibre-ebook.com/3.47.1/calibre-3.47.1.tar.xz : b309933f295cddf05553c60012d8c0376aae732a729688f646466cca55369f9e
license    : GPL-3.0-only
component  : office.viewers
summary    : Calibre eBook Library Manager
description: |
    calibre is a free and open source e-book library management application developed by users of e-books for users of e-books.
builddeps  :
    - pkgconfig(dbus-python)
    - pkgconfig(icu-i18n)
    - pkgconfig(libinput)
    - pkgconfig(libmtp)
    - pkgconfig(mtdev)
    - pkgconfig(poppler)
    - pkgconfig(Qt5Core)
    - pkgconfig(shared-mime-info)
    - pkgconfig(sqlite3)
    - pkgconfig(xkbcommon)
    - chmlib-devel
    - dnspython
    - liberation-fonts-ttf
    - optipng
    - podofo-devel
    - pygments
    - python-apsw
    - python-beautifulsoup4
    - python-css-parser
    - python-dateutil
    - python-html5-parser
    - python-mechanize
    - python-msgpack
    - python-netifaces
    - python-pillow
    - python-psutil
    - python-qt5
    - python-regex
    - python-sip-devel
    - xdg-utils
rundeps    :
    - dnspython
    - liberation-fonts-ttf
    - optipng
    - poppler-utils
    - pygments
    - python-apsw
    - python-backports.functools_lru_cache
    - python-beautifulsoup4
    - python-feedparser
    - python-css-parser
    - python-dateutil
    - python-dbus
    - python-html2text
    - python-html5-parser
    - python-markdown
    - python-mechanize
    - python-msgpack
    - python-netifaces
    - python-pillow
    - python-psutil
    - python-qt5
    - python-regex
setup      : |
    %patch -p1 < $pkgfiles/0001-Remove-mime-setup-conflicts-with-shared-mime-data.patch
    %patch -p1 < $pkgfiles/calibre-no-update.patch
    %patch -p1 < $pkgfiles/use-system-theme.patch
build      : |
    python setup.py build
    python setup.py gui
install    : |
    #Set XDG directories in fakeroot, add read privileges to /usr/share
    export XDG_DATA_HOME=$installdir/usr/share
    export XDG_UTILS_INSTALL_MODE="user"
    python setup.py install --root="%installroot%" --staging-root=%installroot%/usr --prefix=/usr
    %python_compile

    # Restore read permissions for icons
    chmod -R +r $installdir/usr/share/icons

    # Remove MimeTypes from .desktop as it creates unwanted associations
    sed -e "/MimeType/d" -i  $installdir/usr/share/applications/calibre*.desktop
    rm -rf $installdir/usr/share/applications/calibre-{ebook-*,lrfviewer}.desktop
    chmod -R 00755 $installdir/usr/share/applications/calibre-gui.desktop
    install -Dm00644 $workdir/resources/calibre-mimetypes.xml $installdir/usr/share/mime/packages/calibre-mimetypes.xml

    # Use system fonts
    rm $installdir/usr/share/calibre/fonts/liberation/*.ttf
    ln -s /usr/share/fonts/Liberation/*.ttf $installdir/usr/share/calibre/fonts/liberation/

    # Empty folder, also calibre shouldn't own this
    rmdir $installdir/usr/share/desktop-directories
