name       : calibre
version    : 2.41.0
release    : 2
source     :
    - http://download.calibre-ebook.com/2.41.0/calibre-2.41.0.tar.xz : 339e94435bb2d340ba5726e09f26a859262ec99fb624e08efe4acdd3359b2e19
license    :
    - GPL-3.0
    - BSD-3-Clause
summary    : Calibre eBook Library Manager
builddeps  :
    - chmlib-devel
    - libicu-devel
    - pkgconfig(dbus-python)
    - pkgconfig(ImageMagick)
    - pkgconfig(libmtp)
    - pkgconfig(mtdev)
    - pkgconfig(poppler)
    - pkgconfig(Qt5Core)
    - pkgconfig(shared-mime-info)
    - pkgconfig(sqlite3)
    - podofo-devel
    - pyicu
    - python-chardet
    - python-cssutils
    - python-dateutil
    - python-lxml
    - python-mechanize
    - python-psutil
    - python-qt5
    - python-sip-devel
    - python-six
    - xdg-utils
description: |
    calibre is a free and open source e-book library management application developed by users of e-books for users of e-books.
build      : |
    python setup.py build
    python setup.py gui
install    : |
    python setup.py install --root=%installroot%
    mkdir %installroot%/usr
    pushd %installroot%
      mv bin lib share usr
    popd
