name       : calibre
version    : 3.42.0
release    : 106
source     :
    - https://download.calibre-ebook.com/3.42.0/calibre-3.42.0.tar.xz : b51194aecd452e6cea9681889cd1b2f868d379b07413b1dcb8842c363487ad7a
license    : GPL-3.0-only
component  : office.viewers
summary    : Calibre eBook Library Manager
description: |
    calibre is a free and open source e-book library management application developed by users of e-books for users of e-books.
builddeps  :
    - pkgconfig(dbus-python)
    - pkgconfig(icu-i18n)
    - pkgconfig(libinput)
    - pkgconfig(libmtp)
    - pkgconfig(mtdev)
    - pkgconfig(poppler)
    - pkgconfig(Qt5Core)
    - pkgconfig(shared-mime-info)
    - pkgconfig(sqlite3)
    - pkgconfig(xkbcommon)
    - chmlib-devel
    - dnspython
    - liberation-fonts-ttf
    - optipng
    - podofo-devel
    - pygments
    - python-apsw
    - python-beautifulsoup4
    - python-css-parser
    - python-dateutil
    - python-html5-parser
    - python-mechanize
    - python-msgpack
    - python-netifaces
    - python-pillow
    - python-psutil
    - python-qt5
    - python-regex
    - python-sip-devel
    - xdg-utils
rundeps    :
    - dnspython
    - liberation-fonts-ttf
    - optipng
    - poppler-utils
    - pygments
    - python-apsw
    - python-beautifulsoup4
    - python-feedparser
    - python-css-parser
    - python-dateutil
    - python-dbus
    - python-html2text
    - python-html5-parser
    - python-markdown
    - python-mechanize
    - python-msgpack
    - python-netifaces
    - python-pillow
    - python-psutil
    - python-qt5
    - python-regex
setup      : |
    #Remove mime setup, conflicts with shared-mime-data
    sed -e "/self.create_uninstaller()/,/os.rmdir(config_dir)/d" \
        -e "/cc(\['xdg-desktop-menu', 'forceupdate'\])/d" \
        -e "/cc(\['xdg-mime', 'install', MIME\])/d" \
        -i  src/calibre/linux.py

    # Disable Calibre updater
    %patch -p1 < $pkgfiles/calibre-no-update.patch
    %patch -p1 < $pkgfiles/use-system-theme.patch

    # Fixes for QT 5.13
    %patch -p1 < $pkgfiles/fix-qt5.13-build.patch
    %patch -p1 < $pkgfiles/fix-worjaround-colum.patch
build      : |
    python setup.py build
    python setup.py gui
install    : |
    #Set XDG directories in fakeroot, add read privileges to /usr/share
    export XDG_DATA_HOME=$installdir/usr/share
    export XDG_UTILS_INSTALL_MODE="user"
    python setup.py install --root="%installroot%" --staging-root=%installroot%/usr --prefix=/usr
    %python_compile

    # Restore read permissions for icons
    chmod -R +r $installdir/usr/share/icons

    # Remove MimeTypes from .desktop as it creates unwanted associations
    sed -e "/MimeType/d" -i  $installdir/usr/share/applications/calibre*.desktop
    rm -rf $installdir/usr/share/applications/calibre-{ebook-*,lrfviewer}.desktop
    chmod -R 00755 $installdir/usr/share/applications/calibre-gui.desktop
    install -Dm00644 $workdir/resources/calibre-mimetypes.xml $installdir/usr/share/mime/packages/calibre-mimetypes.xml

    # Use system fonts
    rm $installdir/usr/share/calibre/fonts/liberation/*.ttf
    ln -s /usr/share/fonts/Liberation/*.ttf $installdir/usr/share/calibre/fonts/liberation/
