name       : calibre
version    : 2.62.0
release    : 4
source     :
    - http://download.calibre-ebook.com/2.62.0/calibre-2.62.0.tar.xz : ca4e7b13bfbf3950e32c91d163bd31a310fb386375d4c02f4bde8dd7b49b1a97
license    :
    - Artistic-1.0-Perl
    - Apache-2.0
    - BSD-3-Clause
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
    - MIT
    - OFL-1.1
    - Python-2.0
    - Public-Domain
summary    : Calibre eBook Library Manager
component  : desktop.multimedia
builddeps  :
    - pkgconfig(dbus-python)
    - pkgconfig(libmtp)
    - pkgconfig(mtdev)
    - pkgconfig(poppler)
    - pkgconfig(Qt5Core)
    - pkgconfig(shared-mime-info)
    - pkgconfig(sqlite3)
    - chmlib-devel
    - libicu-devel
    - dnspython
    - optipng
    - podofo-devel
    - pygments
    - python-apsw
    - python-cssutils
    - python-dateutil
    - python-lxml
    - python-mechanize
    - python-netifaces
    - python-pillow
    - python-psutil
    - python-qt5
    - python-sip-devel
    - python-six
    - xdg-utils
rundeps    :
    - dnspython
    - optipng
    - poppler-utils
    - pygments
    - python-apsw
    - python-cssutils
    - python-dateutil
    - python-dbus
    - python-lxml
    - python-mechanize
    - python-netifaces
    - python-pillow
    - python-psutil
    - python-qt5
    - python-six
description: |
    calibre is a free and open source e-book library management application developed by users of e-books for users of e-books.
setup      : |
    #Remove mime setup, conflicts with shared-mime-data
    sed -e "/cc(\['xdg-mime', 'install', MIME\])/d" -i  src/calibre/linux.py
build      : |
    %python_setup
    python setup.py gui
install    : |
    #Set XDG directories in fakeroot, add read privileges to /usr/share
    export XDG_DATA_HOME=$installdir/usr/share
    export XDG_UTILS_INSTALL_MODE="user"
    python setup.py install --root=%installroot%/usr
    chmod -R +r $installdir/usr/share

    #Remove MimeTypes from .desktop as it creates unwanted associations
    sed -e "/MimeType/d" -i  $installdir/usr/share/applications/calibre*.desktop
    install -Dm644 $workdir/resources/calibre-mimetypes.xml $installdir/usr/share/mime/packages/calibre-mimetypes.xml
    rm $installdir/usr/bin/calibre-uninstall