name       : calibre
version    : 3.0.0
release    : 38
source     :
    - https://download.calibre-ebook.com/3.0.0/calibre-3.0.0.tar.xz : 7cdaa5c55c8c13d6b5389ee11231c64944f5272297938e426be3a4fcf63a13fe
license    : GPL-3.0
component  : office.viewers
summary    : Calibre eBook Library Manager
description: |
    calibre is a free and open source e-book library management application developed by users of e-books for users of e-books.
builddeps  :
    - pkgconfig(dbus-python)
    - pkgconfig(icu-i18n)
    - pkgconfig(libinput)
    - pkgconfig(libmtp)
    - pkgconfig(mtdev)
    - pkgconfig(poppler)
    - pkgconfig(Qt5Core)
    - pkgconfig(shared-mime-info)
    - pkgconfig(sqlite3)
    - pkgconfig(xkbcommon)
    - chmlib-devel
    - dnspython
    - optipng
    - podofo-devel
    - pygments
    - python-apsw
    - python-cssutils
    - python-dateutil
    - python-lxml
    - python-mechanize
    - python-msgpack
    - python-netifaces
    - python-pillow
    - python-psutil
    - python-qt5
    - python-regex
    - python-sip-devel
    - python-six
    - xdg-utils
rundeps    :
    - dnspython
    - optipng
    - poppler-utils
    - pygments
    - python-apsw
    - python-cssutils
    - python-dateutil
    - python-dbus
    - python-lxml
    - python-mechanize
    - python-msgpack
    - python-netifaces
    - python-pillow
    - python-psutil
    - python-qt5
    - python-regex
    - python-six
setup      : |
    #Remove mime setup, conflicts with shared-mime-data
    sed -e "/self.create_uninstaller()/,/os.rmdir(config_dir)/d" \
        -e "/cc(\['xdg-desktop-menu', 'forceupdate'\])/d" \
        -e "/cc(\['xdg-mime', 'install', MIME\])/d" \
        -i  src/calibre/linux.py
build      : |
    python setup.py build
    python setup.py gui
install    : |
    #Set XDG directories in fakeroot, add read privileges to /usr/share
    export XDG_DATA_HOME=$installdir/usr/share
    export XDG_UTILS_INSTALL_MODE="user"
    python setup.py install --root="%installroot%" --staging-root=%installroot%/usr --prefix=/usr

    #Remove MimeTypes from .desktop as it creates unwanted associations
    sed -e "/MimeType/d" -i  $installdir/usr/share/applications/calibre*.desktop
    rm -rf $installdir/usr/share/applications/calibre-{ebook-*,lrfviewer}.desktop
    chmod -R 0755 $installdir/usr/share/applications/calibre-gui.desktop
    install -Dm644 $workdir/resources/calibre-mimetypes.xml $installdir/usr/share/mime/packages/calibre-mimetypes.xml
