name       : calibre
version    : 2.38.0
release    : 1
source     :
    - http://download.calibre-ebook.com/2.38.0/calibre-2.38.0.tar.xz : 16d665f82d7384ba4799b8fcf20d97abf5cd0a74b925e952d25ab65168ecaa1c
license    :
    - GPL-3.0
    - BSD-3-Clause
summary    : Calibre eBook Library Manager
builddeps  :
    - pkgconfig(dbus-python)
    - pkgconfig(ImageMagick)
    - pkgconfig(mtdev)
    - pkgconfig(poppler)
    - pkgconfig(Qt5Core)
    - pkgconfig(shared-mime-info)
    - python-chardet
    - python-cssselect
    - python-lxml
    - python-mechanize
    - python-psutil
    - python-qt5
    - python-six
    - xdg-utils

description: |
    calibre is a free and open source e-book library management application developed by users of e-books for users of e-books.
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
