name       : calibre
version    : 4.2.0
release    : 117
source     :
    - https://download.calibre-ebook.com/4.2.0/calibre-4.2.0.tar.xz : b1b626acdcc3b29ae96489e7424389161bd6529545f47c0d2b063b99131286d8
license    : GPL-3.0-only
component  : office.viewers
summary    : Calibre eBook Library Manager
description: |
    calibre is a free and open source e-book library management application developed by users of e-books for users of e-books.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(dbus-python)
    - pkgconfig(hunspell)
    - pkgconfig(icu-i18n)
    - pkgconfig(libinput)
    - pkgconfig(libmtp)
    - pkgconfig(mtdev)
    - pkgconfig(poppler)
    - pkgconfig(python3)
    - pkgconfig(shared-mime-info)
    - pkgconfig(sqlite3)
    - pkgconfig(xkbcommon)
    - chmlib-devel
    - dnspython
    - liberation-fonts-ttf
    - optipng
    - podofo-devel
    - pygments
    - python3-qt5
    - python3-sip-devel
    - python-apsw
    - python-beautifulsoup4
    - python-css-parser
    - python-dateutil
    - python-html5-parser
    - python-mechanize
    - python-msgpack
    - python-netifaces
    - python-pillow
    - python-psutil
    - python-qtwebengine
    - python-regex
    - xdg-utils
rundeps    :
    - dnspython
    - liberation-fonts-ttf
    - optipng
    - poppler-utils
    - pygments
    - python3-dbus
    - python3-qt5
    - python-apsw
    - python-beautifulsoup4
    - python-css-parser
    - python-dateutil
    - python-feedparser
    - python-html2text
    - python-html5-parser
    - python-markdown
    - python-mechanize
    - python-msgpack
    - python-netifaces
    - python-pillow
    - python-psutil
    - python-qtwebengine
    - python-regex
environment: |
    export CALIBRE_PY3_PORT=1
setup      : |
    %apply_patches
build      : |
    python3 setup.py build
    python3 setup.py gui
install    : |
    #Set XDG directories in fakeroot, add read privileges to /usr/share
    export XDG_DATA_HOME=$installdir/usr/share
    export XDG_UTILS_INSTALL_MODE="user"
    python3 setup.py install --root="%installroot%" --staging-root=%installroot%/usr --prefix=/usr
    %python3_compile

    # Restore read permissions for icons
    chmod -R +r $installdir/usr/share/icons

    # Remove MimeTypes from .desktop as it creates unwanted associations
    sed -e "/MimeType/d" -i  $installdir/usr/share/applications/calibre*.desktop
    rm -rf $installdir/usr/share/applications/calibre-{ebook-*,lrfviewer}.desktop
    chmod -R 00755 $installdir/usr/share/applications/calibre-gui.desktop
    install -Dm00644 $workdir/resources/calibre-mimetypes.xml $installdir/usr/share/mime/packages/calibre-mimetypes.xml

    # Use system fonts
    rm $installdir/usr/share/calibre/fonts/liberation/*.ttf
    ln -s /usr/share/fonts/Liberation/*.ttf $installdir/usr/share/calibre/fonts/liberation/

    # Empty folder, also calibre shouldn't own this
    rmdir $installdir/usr/share/desktop-directories
